jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java
When JOOQ sends array of bytes to Postgres, it uses the octal format. To do the conversion from binary byte to octal, it uses java.lang.Integer#toOctalString(int) and the byte is automatically casted to integer. It works fine with positive bytes, but not with negative ones.
For example, when [-1] is inserted, [377] should be sent to Posgresql. Instead of that, Java transforms the byte -1 to the integer -1, represented in octal as 377 377 377 377, and jOOQ sends the array [377, 377, 377, 377]!
=> [#3923] Four octects are sent to Postgres for each negative byte in a byte[]

jOOQ/src/main/java/org/jooq/impl/DSL.java
Additional convenience method for something like `select sum(col)`.  Without this method, I have to make assumptions about the return value (BigDecimal) and cast.  With the method, any Field/Value pairing will have the correctly-typed return.
=> Add <T> DSL.coalesce(Field<T>, T)

.gitignore
Trivial, I know, but this corrects .gitignore when the entire jOOQ project is imported into IntelliJ
=> Incorrect IntelliJ directory listings in .gitignore

jOOQ/src/main/java/org/jooq/tools/json/JSONObject.java, jOOQ/src/test/java/org/jooq/tools/JSONObjectTest.java
http://www.jooq.org/javadoc/latest/ is not very clear about JSONObject
taking a map as a parameter in the constructor but calling toString on
the resulting object won't return a JSON string.
I feel things can be improved by either adding something to the documentation
or by having a toString() method which calls toJSONString. This commit
implements the latter.
=> Implements an instance toString() method on JSONObject.

jOOQ/src/main/java/org/jooq/Field.java, jOOQ/src/main/java/org/jooq/impl/AbstractField.java, jOOQ/src/main/java/org/jooq/impl/DSL.java, jOOQ/src/test/java/org/jooq/test/BasicTest.java
Operands of `shl` and `shr` don't need to be same type.
=> Relax type constraint of DSL.shl() and DSL.shr()

jOOQ/src/main/java/org/jooq/impl/DefaultRenderContext.java, jOOQ/src/main/java/org/jooq/impl/DefaultTransactionProvider.java
`ArrayDeque` is faster than `Stack`.
All of method calls of `Stack` are synchronized, but in these codes, it looks like not necessary.
=> Use ArrayDeque as a stack instead of java.util.Stack

jOOQ-codegen-maven/pom.xml, jOOQ-codegen/pom.xml, jOOQ-examples/jOOQ-academy/pom.xml, jOOQ-examples/jOOQ-codegen-gradle/build.gradle, jOOQ-examples/jOOQ-flyway-example/pom.xml, jOOQ-examples/jOOQ-javaee-example/pom.xml, jOOQ-examples/jOOQ-javafx-example/pom.xml, jOOQ-examples/jOOQ-jax-rs-example/pom.xml, jOOQ-examples/jOOQ-nashorn-example/pom.xml, jOOQ-examples/jOOQ-oracle-example/pom.xml, jOOQ-examples/jOOQ-spring-example/pom.xml, jOOQ-examples/jOOQ-spring-guice-example/pom.xml, jOOQ-examples/jOOQ-vertabelo-example/pom.xml, jOOQ-meta-extensions/pom.xml, jOOQ-meta/pom.xml, jOOQ-release/release/template/maven-install.bat, jOOQ-release/release/template/maven-install.sh, jOOQ-scala/pom.xml, jOOQ/pom.xml, jOOQ/src/main/java/org/jooq/impl/HtmlWriter.java, jOOQ/src/main/java/org/jooq/impl/ResultImpl.java, jOOQ/src/test/java/org/jooq/impl/HtmlWriterTest.java, pom.xml
Fix HTML injection
Used commons-lang3's `StringEscapeUtils` to escape field names and values in `ResultImpl.formatHTML`. Separated into another class to allow unit testing.
=> Result.formatHTML() doesn't escape HTML content, which might produce XSS vulnerabilities

jOOQ/src/main/java/org/jooq/impl/BatchMultiple.java, jOOQ/src/main/java/org/jooq/impl/BatchSingle.java, jOOQ/src/test/java/org/jooq/test/MockTest.java
Due to overlap in the method prototypes of `DSLContext#batch(Query)` and
`DSLContext#batch(Query...)` calls intended to invoke the later with a
single argument actually invoke the former. To solve this we check if
`BatchBindStep#bind` was subsequently called and, if not, proceed as if
the var args version was called.
=> [#4554] Ensure batches are sent

jOOQ-codegen/src/main/java/org/jooq/util/GenerationUtil.java
In current version of jOOQ code generation table names like `user.users`, `user.achievements` are transformed to `User_2eusers`, `User_2eachievements` in class names (e.g. for tables, pojos and daos). 
Included patch changes this behaviour to: 
```user.users -> UserUsers```
```user.achievements -> UserAchievements```
i.e. dot is not included into the output, but instead next word is capitalized, producting nice pascal cased names.
=> Do not escape dot in table names during code generation, but use capital case after it

jOOQ/src/main/java/org/jooq/impl/SQLTable.java
…was as how SQLField does it taking value from delegate's toString(). 
It's not perfect, but at least it fixes the bug ("table" is not a good name) and it's consistent.
=> Let SQLTable constructor pass SQL string to AbstractTable parent constructor

jOOQ/src/main/java/org/jooq/impl/MetaDataFieldProvider.java
Some JDBC drivers such as Teradata and Cassandra don't implement `ResultSetMetaData.getSchemaName` and/or `ResultSetMetaData.getTableName` methods, these methods are called in constructor of `MetadataFieldProvider` and would throw `SQLFeatureNotSupportedException`.
=> SQLFeatureNotSupportedException thrown when initalizing MetaDataFieldProvider

jOOQ/src/main/java/org/jooq/impl/SortFieldList.java
The subexpressions between `||` are equal. Looks like this should be `getNullsLast()`.
=> Wrong implementation of internal SortFieldList.nulls()

jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java
[#4338] added support for converting PostgreSQL-formatted timestamps into OffsetDate's OffsetDateTime's, but did not correct for negative offsets.
=> DefaultBindings for OffsetTime and OffsetDateTime handle negative offsets

jOOQ/src/main/java/org/jooq/impl/MetaDataFieldProvider.java
With Amazon Hive JDBC driver, `ResultSetMetaData.getSchemaName()` throws general `SQLException` rather than `SQLFeatureNotSupportedException`.
This is a followup of [pull request 4939](https://github.com/jOOQ/jOOQ/pull/4939).
=> MetaDataFieldProvider should not catch SQLFeatureNotSupportedException from ResultSetMetaData calls

jOOQ-meta/src/main/java/org/jooq/util/h2/H2TableDefinition.java
The H2TableDefinition.java currently only detects IDENTITY columns based on a non-null SEQUENCE_NAME in the column's INFORMATION_SCHEMA. 
In the database I have to deal with, there are composite primary keys defined like this:
```sql
CREATE TABLE foo (
id        BIGINT       NOT NULL               DEFAULT nextval('uid_seq'),
tenant_id BIGINT       NOT NULL,
...
CONSTRAINT pk_user PRIMARY KEY (id, tenant_id))
```
for both Postgres and H2. In Postgres, inserts work as expected (due to the 'returning' clause for the keys), but nor for H2: After `insert into "PUBLIC"."FOO" ("TENANT_ID", ...) values (1, ...)`, no generated key for the id column is returned. In fact, the INFORMATION_SCHEMA does not contain a SEQUENCE_NAME
This patch resolves that, as it adds an alternative condition to detect …
=> Accept column default expressions using sequences as identity columns in H2

jOOQ-manual/src/main/resources/org/jooq/web/manual-3.8.xml
Instead of telling users to copy-paste a snippet of Groovy code into their build,
we now redirect them to a ready-to-use plugin. This provides several benefits:
- the user's build script is shorter
- the configuration syntax is cleaner
- it is easier to upgrade (users just update the plugin version instead of copy-paste-modifying a new snippet)
- the jOOQ team does not need to maintain documentation/examples
- the jOOQ team does not need to troubleshoot problems about generating with Gradle, users can instead open issues for the plugin
=> Recommend jOOQ Gradle plugin

jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java
I think this is safe to just add-in as a default output format when using the scala code generator... I also added as a separate commit cleaning up the `name : Type` to `name: Type`
Reference for `_=`: http://docs.scala-lang.org/style/naming-conventions.html#accessorsmutators
Reference for `name: Type`: http://docs.scala-lang.org/style/types#annotations & http://docs.scala-lang.org/style/declarations#methods
=> Generate Scala-Style Getter/Setter for Record classes

jOOQ-examples/jOOQ-spark-chart-example/src/main/java/org/jooq/example/chart/SakilaReportService.java
As the graph suggests cumulative earnings are per store, not over all stores.
See
```sql
select 
"public"."store"."store_id", 
cast("public"."payment"."payment_date" as date) "payment_date", 
sum("public"."payment"."amount") "amount",
sum(sum("public"."payment"."amount")) over (partition by "public"."store"."store_id" order by cast("public"."payment"."payment_date" as date) asc) "cumulative_per_store",
sum(sum("public"."payment"."amount")) over (order by cast("public"."payment"."payment_date" as date) asc) "cumulative_total"
from "public"."store"
join "public"."inventory"
using("store_id")
join "public"."rental"
using("inventory_id")
join "public"."payment"
using("rental_id")
group by 
cast("public"."payment"."payment_date" as date), 
"public"."store"."store_id"
order by …
```
=> Cumulative Earnings example in jOOQ-spark-chart-example is wrong

jOOQ-scala/src/main/scala/org/jooq/scala/Conversions.scala
See thread: http://stackoverflow.com/questions/34745066/dummyimplicits-is-this-used-and-how for how/why the DummyImplicit(s) are used to get around typeerasure issues
=> Fix the type-erasure issue for scala vararg helpers in org.jooq.scala.Conversions using scala.predef.DummyImplicit

jOOQ-codegen-maven/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Added hint for m2e to run generate goal on "configuration change", which basically
means on project imports and when pom.xml has bee modified. This makes
jOOQ projects compile properly when imported and also (for some weird reason)
fixes autoconfiguration of classpath for the generated resources.
Without this change most jOOQ+Eclipse users will need to add lots of Eclipse
specific dirt to their pom.xml file.
Closes #5582
=> Added hint for m2e to behave

jOOQ/src/main/java/org/jooq/tools/Convert.java, jOOQ/src/test/java/org/jooq/tools/ConvertTest.java
So this is not ready for merge, has some outstanding issues. 
- tests - I made `ConvertAll` package private so I could slap some unit tests in there. What is the correct place for tests?
- API - as you can see from the test, when converting from a collection you have to use `ConvertAll` directly, since adding another `convert(Collection<?> collection, Class<? extends T[]> type)` method would conflict, and changing the existing one might not be what you want to do.
=> #3062 Work on adding ability to convert between collections and arrays.

jOOQ-manual/src/main/resources/org/jooq/web/manual-3.9.xml
You can't do `count(*)` in Java.
=> Fix typo in `having` example java code

jOOQ/src/main/java/org/jooq/impl/DSL.java, jOOQ/src/main/java/org/jooq/impl/LocalDateAdd.java, jOOQ/src/main/java/org/jooq/impl/LocalDateDiff.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
This PR aims to close issue #5645.
It introduces the following new methods in overloaded variants inside the DSL:
- localDateAdd
- localDateSub
- localDateDiff
=> Add localDateAdd() localDateSub(), localDateDiff() support to DSL

jOOQ-examples/jOOQ-spring-boot-example/pom.xml
Jooq starter includes jdbc starter as transitive dependency, so we can use this and jooq is obtained from jooq starter.
also upgrades to latest spring boot version
=> In jOOQ-spring-boot-example, use jooq starter instead of jdbc starter

jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java
This is a proposal to resolve the issue described in #6705.
=> [#6705] Avoid generating code with a redundant cast

jOOQ/src/main/java/org/jooq/types/UInteger.java, jOOQ/src/main/java/org/jooq/types/ULong.java, jOOQ/src/main/java/org/jooq/types/UShort.java
Now, UNumber.toBigInteger implemented as new BigInteger(toString());
BigInteger is immutable, so we can just return this.value for ULong, and use BigInteger.valueOf for other types
=> Optimization of {ULong,UInteger,UShort}.toBigInteger

jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java
I don't know enough about why this was deprecated: https://github.com/jOOQ/jOOQ/blob/f58e7d7ef6430058925551fc673ea74f9c9d7cc3/jOOQ/src/main/java/org/jooq/impl/TableImpl.java#L146 but this PR basically does the same thing, just more explicitly for the scala-only generated code.
My instinct suggests that this PR might not actually be the correct solution, and the one helper function should actually be "undeprecated" since the original `JavaGenerator` usage seems like a cleaner API interface with `TableImpl` .. are there additional deprecation warnings on the java side here: https://github.com/jOOQ/jOOQ/blob/eec46ca0835bb5e5f433ad76adc75ed31fabb0bc/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L3669-L3670 ?  (although those look like they aren't using `TableImpl` but a …
=> [7051] Fix generated scala deprecation warning

jOOQ/src/main/java/org/jooq/impl/DefaultDSLContext.java
Exception message should use `TransactionalRunnable` when running `TransactionalRunnable` with `ThreadLocalTransactionProvider `.
This should be better error message to show which line goes wrong.
=> Fix exception message in transaction

jOOQ/src/main/java/org/jooq/impl/TableImpl.java, jOOQ/src/main/java/org/jooq/impl/Tools.java
This is following up my [post in jOOQ UG](https://groups.google.com/forum/#!topic/jooq-user/YXUtvMP3GFI) 
I'm terribly sorry if it's a hack! I tested that it solves my specific scenario but I don't know how to check whether it doesn't create a problem.
Anyway, @lukaseder, please regard this as a suggestion, nothing more! Thank you!
=> Allow usage of derived table as aliased parameter of TableImpl constructor

jOOQ/pom.xml, jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
My naive attempt to leverage Kotlin `@Metadata` when mapping to Kotlin data classes.
Only [primary constructors](https://kotlinlang.org/docs/reference/classes.html#constructors) are considered. If the number of parameter matches the number of fields in the record, their names are checked. If all the names match the record is then mapped to the corresponding parameters by the names. 
If some of the conditions are not met an exception is thrown. I don't think we should default to any other mapping strategies for Kotlin data classes as not-matching the property names can lead to silent errors.
=> [#7324] Support Kotlin data classes in DefaultRecordMapper

jOOQ-meta/src/main/java/org/jooq/util/BufferedLog.java, jOOQ/src/main/java/org/jooq/Log.java, jOOQ/src/main/java/org/jooq/conf/Settings.java, jOOQ/src/main/java/org/jooq/impl/ExecuteListeners.java, jOOQ/src/main/java/org/jooq/tools/JooqLogger.java, jOOQ/src/main/java/org/jooq/tools/LoggerListener.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
Let me know what you think. Here's my random collection of questions/concerns/comments:
- The version of Log4J you're using doesn't have `isWarnEnabled()` or `isErrorEnabled()`. I used a method that takes a deprecated enum instead, which I'm not super happy about.
- Is there a reason Settings isn't using Object.equals and Object.hash? The custom implementation is kind of verbose.
- This doesn't let you log with an SFL4J marker. That's kind of tricky to pull off, since you also support Log4J and java.util.Logging. I guess let people set a marker in the Settings, then only use it if logging with SFL4J?
- I treat FATAL as ERROR. Let me know if that's okay.
=> #7301: Allow customization of LoggerListener

jOOQ-examples/jOOQ-spring-boot-example/src/test/java/org/jooq/example/spring/TransactionTest.java
I guess it should assert rollback1 and rollback2 instead.
=> Spring boot example test repeats identical assertion

pom.xml
Prior to this commit, the `maven-compiler-plugin` **3.7.0** places jars on the class path which need to be placed on the module path. See errors at https://travis-ci.org/jOOQ/jOOQ/builds/400924646#L2003
Using `maven-compiler-plugin` **3.7.1-SNAPSHOT** solves this issue.
Related bug: https://issues.apache.org/jira/browse/MCOMPILER-336
=> Upgrade to maven-compiler-plugin 3.7.1-SNAPSHOT

jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
`parameterValues` is shared between threads and can be concurrently modified, causing the inconsistencies described by the issue.
=> [#7764] Race condition in DefaultRecordMapper 

jOOQ/src/main/java/org/jooq/Field.java
This fixes #7938.
---
The SQL-equivalent part of this method's documentation was wrongly indicating that it:
> translates to `this not ilike` ... in POSTGRES, or to `lower(this) not like lower` ... in all other dialects.
---
I removed the `not`.
Could not find any other similar mistake – I'm pretty sure that was an isolated case.
=> Fix Javadoc entry for Field#containsIgnoreCase

jOOQ/src/main/java/org/jooq/impl/Coerce.java
The Coerce'ed field renders the full qualified name in SQL, but the field-name is used for comparison, so the name should match the rendered SQL.
After updating to jOOQ 3.11.4 some of our query creation code fails as it compares Coerce'ed table fields and they are not equal anymore (as they where before). With the proposed change the code works again as expected.
=> In Coerce use the qualified name so that fields can be compared again

jOOQ-examples/Sakila/postgres-sakila-db/postgres-sakila-schema.sql
Function `get_customer_balance` declared in postgres_sakila_schema.sql uses a function called IF that doesn't exist in PostgreSQL (probably a remnant from the original MySQL version).
Replace the IF with a corresponding CASE statement, including appropriate conversions for the intervals.
=> Sakila/PostgreSQL: Replace nonexisting IF with CASE

jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
Fixes: #8004
trim Kotlin property names to handle edgecase for booleans
=> [#8004] Handle edgecase for Kotlin boolean type

jOOQ-examples/Sakila/postgres-sakila-db/postgres-sakila-schema.sql, jOOQ/src/main/resources/META-INF/ABOUT.txt
When using the Sakila DB with the Docker image postgres:12.1 the initialisation fails with:
`ERROR:  language "plpgsql" already exists`
With PostgreSQL 8.4 (see [1]) and earlier it was only possible to execute:
`CREATE [ PROCEDURAL ] LANGUAGE name`
Starting with PostgreSQL 9.0 (see [2]) it is possible to execute:
`CREATE [ OR REPLACE ] [ PROCEDURAL ] LANGUAGE name`
This commit makes the SQL script incompatible with PostgreSQL 8.4 and earlier.
[1] https://www.postgresql.org/docs/8.4/sql-createlanguage.html
[2] https://www.postgresql.org/docs/9.0/sql-createlanguage.html
=> Sakila/PostgreSQL: Don't fail if language plpgsql already exists

jOOQ-examples/Sakila/oracle-sakila-db/README.md, jOOQ-examples/Sakila/oracle-sakila-db/oracle-sakila-delete-data.sql, jOOQ-examples/Sakila/oracle-sakila-db/oracle-sakila-schema.sql
This PR fixes the Sakila install scripts for Oracle Database and cleans up some of the others.
It also provides an installation ReadMe.
=> Fix Sakila install scripts for Oracle Database

codegen.java, jbang-catalog.json
This PR adds jbang catalog so you can run jooq codegen using jbang.dev
i.e. given a `library.xml` with settings for postgres the simplest way
to run using postgres driver is as follows:
`jbang --deps org.postgresql:postgresql:42.2.14 codegen@maxandersen/jooq/jbang library.xml`
Notice the `codegen@maxandersen/jooq/jbang` - that is just where this PR lives right not:
`codegen` script at `maxandersen` github user's `jooq` git repo in the `jbang` branch.
If you push this commit it gets shorten to:
`jbang --deps org.postgresql:postgresql:42.2.14 codegen@jooq/jooq library.xml`
And if we make a `jooq/jbang-catalog` repo it can be as short as:
`jbang --deps org.postgresql:postgresql:42.2.14 codegen@jooq library.xml`
In case users want to use a specific version of the codegenerator they can do …
=> [jOOQ/jOOQ#11492] Add jbang catalog

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
The single-key case was correctly mapped for this, but not the multi-key case.
=> Fix generating multi-key DAOs with Java records

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java
Spotted locally; there is a double negation in this sentence:
> This code generation run has not produced any file modifications.
> This means, the schema has not changed, and no other parameters (jOOQ version, driver version, database version,
> and any configuration elements) have not changed either.
=> Fix typo in log message

jOOQ-meta/src/main/resources/org/jooq/meta/xsd/jooq-codegen-3.18.0.xsd
This wasn't me, the IDE made me do it. :wink: 
(I think "helps in identifying" would also be correct.)
=> Fix incorrect grammar in XSD documentation

jOOQ/src/main/java/org/jooq/impl/DSL.java
Just a one-character precent->percent typo fix similar in nature to #14182
=> [#14182] Fix typo in percentRank javadoc comment

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
Fixes https://github.com/jOOQ/jOOQ/issues/14801 by removing an extra parameters for String interpolation when generating Java code, which resulted in code that wouldn't compile.
=> [#14801] Fix Java String generation for non-nullable arrays

jOOQ/src/main/java/org/jooq/impl/R2DBC.java
This PR fixes #17094 
**Description:**
When using DSLContext with R2DBC's ConnectionFactory, particularly with a ConnectionPool, connections are not always properly returned to the pool under heavy query load. This leads to connection leakage, which gradually reduces the system's performance and eventually prevents any further database queries.
**Root Cause:**
The problem arises when all connections are leased from the ConnectionPool and additional queries are queued. If a pending query is canceled before it gets a connection, the cancellation isn’t handled correctly. The request remains pending, and when it finally acquires a connection, that connection is not returned to the pool, causing a leak.
**Proposed Solution:**
_Improved Cancellation Handling:_
The ConnectionSubscriber class …
=> [jOOQ/jOOQ#17094] Prevent connection leaks on subscription cancellation in R2DBC

jOOQ/src/main/java/org/jooq/impl/BatchSingle.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
Currently the Javadoc of `BatchBindStep` interface states that calling `BatchBindStep bind(Map<String, Object>... namedBindValues)` is the same as calling `BatchBindStep bind(Map<String, Object> namedBindValues)` several times: https://github.com/jOOQ/jOOQ/blob/d0cdd0c8200e7175477727615cf15425645f90b7/jOOQ/src/main/java/org/jooq/BatchBindStep.java#L140
This is not true performance wise, I noticed a significant performance boost when using the first one. This was due to the numerous calls to `extractBindValues` when using the second one several times.
=> Performance improvement in BatchSingle class
