jOOQ/jOOQ

jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java
copied binding support from generateUDT to generateRoutine
=> Code generator does not apply binding to Routines

jOOQ/src/main/java/org/jooq/impl/DefaultDSLContext.java
lastId implementation for Postgres
=> Add PostgreSQL support for DSLContext.lastId()

jOOQ-examples/jOOQ-spring-boot-example/pom.xml, jOOQ-examples/jOOQ-spring-boot-example/src/main/java/org/jooq/example/spring/Application.java
Simplified Spring Boot Configuration.
Upgraded jOOQ version to 3.5.4.
This is an intermediate upgrade until https://github.com/spring-projects/spring-boot/pull/2804 gets merged into Spring Boot master.
=> Upgrade Spring Boot version in example to 1.2.3.

jOOQ-manual/src/main/resources/org/jooq/web/manual-3.8.xml
As discussed in https://github.com/jOOQ/jOOQ/issues/5289
=> Add nullable(false) in "The CREATE statement" part

jOOQ-codegen/src/main/java/org/jooq/util/GenerationTool.java, jOOQ-meta/src/main/java/org/jooq/util/AbstractDatabase.java, jOOQ-meta/src/main/java/org/jooq/util/AbstractTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/Database.java, jOOQ-meta/src/main/java/org/jooq/util/cubrid/CUBRIDTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/derby/DerbyTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/h2/H2TableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/hsqldb/HSQLDBTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/mysql/MySQLTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/postgres/PostgresMaterializedViewDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/postgres/PostgresTableDefinition.java, jOOQ-meta/src/main/java/org/jooq/util/postgres/PostgresTableValuedFunction.java, jOOQ-meta/src/main/java/org/jooq/util/sqlite/SQLiteTableDefinition.java, jOOQ-meta/src/main/resources/xsd/jooq-codegen-3.9.0.xsd
…r configuration
Add feature for all databases/dialects that may create ColumnDefinitions with isIdentity = true
=> Add <syntheticIdentities> regular expression to code generator configuration

jOOQ-codegen/src/main/java/org/jooq/util/GenerationUtil.java, jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java
Don't merge this yet, I'm still playing with it, but curious if your integration tests say anything...
=> ScalaGenerator should follow Scala Style Guide in generated code

jOOQ/src/main/java/org/jooq/InsertOnConflictDoUpdateStep.java, jOOQ/src/main/java/org/jooq/impl/InsertImpl.java, jOOQ/src/main/java/org/jooq/impl/InsertQueryImpl.java
Suggestion of implementation for ticket #5699
=> [#5699] Specify field for instruction "on conflict … do ignore" 

jOOQ/src/main/java/org/jooq/Field.java, jOOQ/src/main/java/org/jooq/impl/AbstractField.java, jOOQ/src/main/java/org/jooq/impl/ContainsIgnoreCase.java
=> [5619] Add Field.containsIgnoreCase() to support Postgres' ILIKE operator

jOOQ-manual/src/main/resources/org/jooq/web/manual-2.5.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-2.6.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.0.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.1.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.2.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.3.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.4.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.5.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.6.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.7.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.8.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual-3.9.xml, jOOQ-manual/src/main/resources/org/jooq/web/manual.xml
Open issue is here: https://github.com/jOOQ/jOOQ/issues/6063
=> [#6063] change Field.equal() and Field.notEqual() to Field.eq() and Field.ne() in manual pages

jOOQ-examples/Sakila/sql-server-sakila-db/sql-server-sakila-schema.sql
- add GO after DB creation
- fix datetime formating
=> SQL Server compatability

jOOQ/src/main/java/org/jooq/tools/Convert.java
Hello!
I'm wondering if there's a reason we haven't got a simple enum to enum.
I might have missed it or something but if it doesn't exist it would be nice to have it.
=> Add better Enum to Enum conversion support in org.jooq.tools.Convert

jOOQ/src/main/java/org/jooq/impl/JoinTable.java
This improves the error messages when join onKey() fails, as discussed in #6266
I have signed https://www.jooq.org/legal/contributions as Richard Bradley
=> Improve onKey() join error messages, when join expression is ambiguous

jOOQ-examples/jOOQ-spring-boot-example/src/main/resources/application.properties
Corrected property name as per spring boot document https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_customizing_jooq
=> Fix change in property key 

jOOQ/src/main/java/org/jooq/tools/jdbc/JDBCUtils.java
overload the JDBCUtils.dialect method to recognize and return an appropriate dialect
=> [#6814] overload the JDBCUtils.dialect method

jOOQ-release/release/template/maven-deploy.bat
There are some errors in maven-deploy.bat. I'm not sure anyone could have got to know how to use the script without noticing and working around these...
=> Fix maven deploy

jOOQ/src/main/java/org/jooq/impl/ParserImpl.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
Noticed this seems relatively simple to fix so thought I'd knock it out. But if there's some context I'm missing, feel free to close.
Fixes #7021
=> [#7021] Add parser support for DATETIME data type.

jOOQ/src/main/java/org/jooq/impl/WindowDefinitionImpl.java
I think by structure/indentation/purpose there’s a dangling then branch in the original change.
=> Make visiting a window actually conditional on its nullity.

jOOQ/src/main/java/org/jooq/conf/QuoteEscaping.java, jOOQ/src/main/java/org/jooq/conf/Settings.java, jOOQ/src/main/java/org/jooq/conf/SettingsTools.java, jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java, jOOQ/src/main/java/org/jooq/impl/Tools.java, jOOQ/src/main/resources/xsd/jooq-runtime-3.11.0.xsd
https://github.com/jOOQ/jOOQ/issues/5873
=> [#5873] Add Setting.quoteEscaping to allow for alternative escaping of single quote

jOOQ-codegen-maven/src/main/java/org/jooq/codegen/maven/Plugin.java
Hi, @lukaseder! 
Thank you for jOOQ, it's great! Recently, I upgraded a large maven build to JDK10 (from JDK8), and the jOOQ build step started failing with "too many open files". It seems to be related to the fact that `java.util.zip.ZipFile#finalize` used to close the files on [JDK <= 9](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/zip/ZipFile.java#l662), but it was deprecated for removal and in [JDK10](http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/classes/java/util/zip/ZipFile.java#l910), and now it has an empty body. 
I ran `lsof` to see the list of open files.
```
count | filename
...
7 /var/lib/buildkite-agent/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar
7 /var/lib/buildkite-agent/.m2/repository/software/amazon/ion/ion-java/1.0.2/i …
```
=> Close the Maven Plugin's URLClassLoader after code generation

CONTRIBUTING.md
=> Spelling in CONTRIBUTING.md

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java
Tiny PR, contributor agreement signed.
=> Make generatePojoMultiConstructor in JavaGenerator protected

jOOQ-examples/Sakila/db2-sakila-db/db2-sakila-schema.sql
This makes it possible to run script from clp without changing stmt terminator. Verified with:
#> db2 +c -s -tf  db2-sakila-schema.sql
=> Add empty comment after stmt in trigger.

jOOQ-codegen/src/main/java/org/jooq/codegen/AbstractGenerator.java, jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java
=> [jOOQ/jOOQ#12992] Automatically enable table generation if indexes are enabled

jOOQ/src/main/resources/META-INF/ABOUT.txt
I missed to add this in #12993.
=> [jOOQ/jOOQ#12992] Add contributor

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java, jOOQ/src/main/resources/META-INF/ABOUT.txt
Another, slightly more convoluted, solution which fixes the same issue as: https://github.com/jOOQ/jOOQ/pull/13009
=> [#13008] Unquote keyword when mapping one to many relation

jOOQ-examples/jOOQ-testcontainers-flyway-example/pom.xml
Added code to close test-container.
Fixes [jOOQ/jOOQ#13635]
=> Close testcontainer in example

.github/ISSUE_TEMPLATE/feature_request.yaml
feature_request.yaml had two "use case" fields
Credits go to @pmouawad https://github.com/apache/jmeter/pull/5710#pullrequestreview-1119291869
=> Fix "Use case" -> "Possible solution" field name in feature request template

jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java
=> Correctly hint nullability of getSchema() method
